version: '3.4'

# Run docker-compose run start-db first!!  The DB must be running for the app image to build

services:
  todoapi:
    image: kjtully/dotnet-distributed-otel-appd-todoapi:${TAG:-latest}
    ports:
      - "5000:5000"
    #build:
    #  context: .
    #  dockerfile: TodoApi/docker/Dockerfile
    restart: on-failure
    environment:
      # AppDynamics agent configs (defined in .env file)
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "TodoApi"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: "$APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX-api"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME: "$APPDYNAMICS_AGENT_REUSE_NODE_NAME"
      #APPDYNAMICS_AGENT_NODE_NAME: "$APPDYNAMICS_AGENT_NODE_NAME"
      APPDYNAMICS_PREVIEW_FEATURE_ENABLED: "$APPDYNAMICS_PREVIEW_FEATURE_ENABLED"
      RABBITMQ_HOSTNAME: "$RABBITMQ_HOSTNAME"
      JAEGER_HOSTNAME: "$JAEGER_HOSTNAME"
    depends_on:
      - jaeger
      - rabbitmq

  todomvcui:
    image: kjtully/dotnet-distributed-otel-appd-todomvcui:${TAG:-latest}
    ports:
      - "60000:60000"
    #build:
    #  context: .
    #  dockerfile: TodoMvcUi/docker/Dockerfile
    environment:
      TODOAPI_HOSTNAME: "$TODOAPI_HOSTNAME"
      # AppDynamics agent configs (defined in .env file)
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "TodoMvcUi"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: "$APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX-mvcui"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME: "$APPDYNAMICS_AGENT_REUSE_NODE_NAME"
      #APPDYNAMICS_AGENT_NODE_NAME: "$APPDYNAMICS_AGENT_NODE_NAME"
      APPDYNAMICS_PREVIEW_FEATURE_ENABLED: "$APPDYNAMICS_PREVIEW_FEATURE_ENABLED"
      APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      RABBITMQ_HOSTNAME: "$RABBITMQ_HOSTNAME"
      JAEGER_HOSTNAME: "$JAEGER_HOSTNAME"
    depends_on:
      - jaeger
      - rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "wget", "localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 5

