apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: traffic
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine 
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
          name: traffic
        - containerPort: 15672
          name: management
#apiVersion: v1
#kind: Pod
#metadata:
#  creationTimestamp: null
#  labels:
#    run: rabbitmq
#  name: rabbitmq
#spec:
#  containers:
#  - image: rabbitmq:3-management-alpine
#    name: rabbitmq
#    ports:
#    - containerPort: 5672
#    - containerPort: 15672
#  dnsPolicy: ClusterFirst
#  restartPolicy: Never
