apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvcui
  labels:
    app: todomvcui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todomvcui
  template:
    metadata:
      labels:
        app: todomvcui
    spec:
      containers:
      - name: todomvcui
        image: kjtully/dotnet-distributed-otel-appd-todomvcui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 60000
        env:
        - name: TODOAPI_HOSTNAME
          value: 'todoapi'
        - name: RABBITMQ_HOSTNAME
          value: 'rabbitmq'
        - name: JAEGER_HOSTNAME
          value: 'jaeger-agent'
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: ''
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: ''
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          value: ''
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: ''
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          value: ''
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: 'dotnetcore-linux-distributed-kubernetes' 
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: 'TodoMvcUi'
        - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME
          value: 'true'
        - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
          value: 'todomvcui'
        - name: APPDYNAMICS_BROWSER_EUM_APPKEY
          value: ''
        - name: APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP
          value: 'http://cdn.appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS
          value: 'https://cdn.appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_BEACON_HTTP
          value: 'http://col.eum-appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS
          value: 'https://col.eum-appdynamics.com'
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: '3892'
        - name: APPDYNAMICS_PREVIEW_FEATURE_ENABLED
          value: 'true'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: todomvcui
  labels:
    app: todomvcui
spec:
  ports:
  - port: 60000
    targetPort: 60000
    protocol: TCP
  selector:
    app: todomvcui
  type: NodePort
